<a href="https://colab.research.google.com/github/cij1012/pytorch/blob/cij1012-pytorch1/3-min-pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
import torch.autograd

In [3]:
import torch.nn

In [4]:
import torch.optim
import torch.utils.data
import torch.onnx

In [5]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [6]:
print(x.size(), x.shape, x.ndimension())

torch.Size([3, 3]) torch.Size([3, 3]) 2


In [7]:
x = torch.unsqueeze(x, 0)
print(x)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [8]:
print(x.size(), x.shape, x.ndimension())

torch.Size([1, 3, 3]) torch.Size([1, 3, 3]) 3


In [9]:
x = x.view(9)
print(x)
print(x.size(), x.shape, x.ndimension())

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([9]) torch.Size([9]) 1


In [13]:
x = x.view(3,1,3)
print(x)

tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])


In [15]:
w = torch.randn(5,3, dtype=torch.float)
x = torch.tensor([[1.0,2.0],[3.0,4.0],[5.0,6.0]])
print(w.size())
print(x.size())
print(w)
print(x)

torch.Size([5, 3])
torch.Size([3, 2])
tensor([[-0.2533,  1.2558,  0.5416],
        [ 1.2400,  0.2645,  0.8932],
        [ 0.0133,  0.1200, -1.0618],
        [-0.3923, -0.6881,  0.1090],
        [-0.2979,  0.0865, -0.0615]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [20]:
b = torch.randn(5,2, dtype=torch.float)
print(b)

tensor([[ 0.0520, -0.0251],
        [ 1.7154,  0.5088],
        [-1.2375,  0.6215],
        [-0.1867,  0.6291],
        [ 1.2965, -0.3465]])


In [22]:
# 행렬곱  (5,3) * (3,2) = (5,2)
wx = torch.mm(w,x)
print(wx)
print(wx.size())

tensor([[ 6.2220,  7.7661],
        [ 6.4995,  8.8972],
        [-4.9360, -5.8645],
        [-1.9117, -2.8831],
        [-0.3457, -0.6186]])
torch.Size([5, 2])


In [23]:
# 행렬간의 합
result = wx + b
print(result.size())
print(result)

torch.Size([5, 2])
tensor([[ 6.2740,  7.7410],
        [ 8.2149,  9.4060],
        [-6.1735, -5.2430],
        [-2.0984, -2.2539],
        [ 0.9508, -0.9650]])


In [29]:
# Auto grad
w = torch.tensor(1.0, requires_grad=True)

In [30]:
a = w*3

In [31]:
l = a**2

In [32]:
l.backward()
print('l을 w로 미분한 값은 {}'.format(w.grad))

l을 w로 미분한 값은 18.0


In [36]:
# 경사하강법으로 이미지 복원하기

import pickle
import matplotlib.pyplot as plt

broken_image = torch.FloatTensor( pickle.load(open('/content/broken_image_t.p','rb'), encoding='latin1'))
plt.imshow(broken_image.view(100,100))

UnpicklingError: ignored

In [38]:
a = pickle.load(open('/content/broken_image_t.p','rb'), encoding='latin1')

UnpicklingError: ignored