<a href="https://colab.research.google.com/github/cij1012/pytrorch/blob/master/%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

선형회귀


In [0]:
import torch

In [4]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [0]:
x_train = torch.FloatTensor([[2],[4],[6]])
y_train = torch.FloatTensor([[3],[6],[9]])

In [6]:
print(x_train,x_train.shape)

tensor([[2.],
        [4.],
        [6.]]) torch.Size([3, 1])


y = Wx+b

In [7]:
W = torch.zeros(1,requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [8]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


H(x) = Wx+b

In [9]:
H = x_train*W + b
print(H)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


cost = MSE

In [11]:
cost = torch.mean((H-y_train)**2)
print(cost)

tensor(42., grad_fn=<MeanBackward0>)


In [0]:
optimizer = optim.SGD([W,b], lr=0.01)

In [0]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [15]:
# 데이터
x_train = torch.FloatTensor([[2],[4],[6]])
y_train = torch.FloatTensor([[3],[6],[9]])
# 모델 초기화
W = torch.zeros(1,requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):
  # H(가설) 계산
  H = x_train * W + b
  # cost 계산
  cost = torch.mean((H - y_train) ** 2)
  # cost로 H 계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #100번 마다 로그 출력
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W:{:.3f}, b: {:.3f} Cost : {:.6f}.'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/2000 W:0.560, b: 0.120 Cost : 42.000000.
Epoch  100/2000 W:1.449, b: 0.235 Cost : 0.007916.
Epoch  200/2000 W:1.461, b: 0.179 Cost : 0.004581.
Epoch  300/2000 W:1.471, b: 0.136 Cost : 0.002651.
Epoch  400/2000 W:1.478, b: 0.103 Cost : 0.001534.
Epoch  500/2000 W:1.483, b: 0.079 Cost : 0.000888.
Epoch  600/2000 W:1.487, b: 0.060 Cost : 0.000514.
Epoch  700/2000 W:1.490, b: 0.045 Cost : 0.000297.
Epoch  800/2000 W:1.493, b: 0.035 Cost : 0.000172.
Epoch  900/2000 W:1.494, b: 0.026 Cost : 0.000100.
Epoch 1000/2000 W:1.496, b: 0.020 Cost : 0.000058.
Epoch 1100/2000 W:1.497, b: 0.015 Cost : 0.000033.
Epoch 1200/2000 W:1.497, b: 0.012 Cost : 0.000019.
Epoch 1300/2000 W:1.498, b: 0.009 Cost : 0.000011.
Epoch 1400/2000 W:1.499, b: 0.007 Cost : 0.000006.
Epoch 1500/2000 W:1.499, b: 0.005 Cost : 0.000004.
Epoch 1600/2000 W:1.499, b: 0.004 Cost : 0.000002.
Epoch 1700/2000 W:1.499, b: 0.003 Cost : 0.000001.
Epoch 1800/2000 W:1.500, b: 0.002 Cost : 0.000001.
Epoch 1900/2000 W:1.500, b: 0.

파이토치로 구현하기

In [0]:
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [0]:
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [18]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr = 1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  # H 계산
  H = x1_train * w1 + x2_train * w2 + x3_train * w3 + b
  # cost 계산
  cost = torch.mean((H - y_train) **2)
  # cost로 H 계산
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0 :
    print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
    epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
    ))   

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319497
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266215
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


행렬 연산 고려하여 파이토치로

In [0]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [20]:
print(x_train.shape, y_train.shape)

torch.Size([5, 3]) torch.Size([5, 1])


In [23]:
W = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1,requires_grad=True)

optimizer = optim.SGD([W,b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
  H = x_train.matmul(W) + b
  cost = torch.mean((H - y_train) ** 2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch {:4d}/{} H: {} Cost: {:.6f}'.format(
  epoch, nb_epochs, H.squeeze().detach(), cost.item()
  ))  

Epoch    0/20 H: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 H: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 H: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 H: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 H: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 H: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371071
Epoch    6/20 H: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 H: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 H: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 H: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 H: tensor([152.3454, 183.1161, 180.4231, 196.4765, 139.6732]) Cost: 1.897688
Epoch   11/20 H: 

nn.Module로 구현하는 선형회귀


In [0]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [0]:
model = nn.Linear(1,1)

In [26]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [34]:
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

nb_epochs = 2000
for epoch in range(nb_epochs+1):

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [35]:
new_var = torch.FloatTensor([[4.0]])
pred_y - model(new_var)
print(pred_y)

tensor([[1.6197]], grad_fn=<AddmmBackward>)


In [31]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]]) 
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[1.6197]], grad_fn=<AddmmBackward>)
